FROM ubuntu:latest

LABEL maintainer="zklib"

WORKDIR /workdir

ENV TZ=Europe/Amsterdam
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN \
    apt-get update && apt-get install -y \
        clang-format \
        pmccabe \
    && rm -rf /var/lib/apt/lists/*

